[[redirects]]
  from = "/3.0/recipes.html"
  to = "/3.0/guides.html"
  status = 301
  force = false

[[redirects]]
  from = "/3.0/localization.html"
  to = "/3.0/i18n.html"
  status = 301
  force = false

[[redirects]]
  from = "/3.0/localization"
  to = "/3.0/i18n"
  status = 301
  force = false

[[redirects]]
  from = "/3.0/:dir/:page.*"
  to = "/3.0/:dir/:page"
  status = 301
  force = false

[[redirects]]
  from = "/3.0/:page.md"
  to = "/3.0/:page"
  status = 301
  force = false

[[redirects]]
  from = "/3.0/recipes/*"
  to = "/3.0/guides/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/3.0/gemfile-environment-variables.html"
  to = "/3.0/gem-server-authentication.html"
  status = 301
  force = false

# Redirects for 2.0 versions
# -------------------------

[[redirects]]
  from = "/2.0/stimulus-controllers.html"
  to = "/2.0/custom-fields.html#use-pre-built-stimulus-controllers"
  status = 301
  force = false

# Redirects for old versions
# -------------------------

[[redirects]]
  from = "/1.0/*"
  to = "https://v1-docs.avohq.io/1.0/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/0.1/*"
  to = "https://v1-docs.avohq.io/0.4.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/0.4.x/*"
  to = "https://v1-docs.avohq.io/0.4.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/0.5.x/*"
  to = "https://v1-docs.avohq.io/0.5.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/0.x/*"
  to = "https://v1-docs.avohq.io/0.4.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/1.0/fields-reference.html"
  to = "https://v1-docs.avohq.io/1.0/field-options.html"
  status = 301
  force = false
